package ilab.core.domain.user;

public enum QuotationStatus
{

	QUOTE_REJECTED_PARTNER, QUOTE_ACCEPTED_PARTNER, QUOTE_EXPIRED, QUOTE_SENT, WAIT_QUOTE, QUOTE_ACCEPTED_USER,
	QUOTE_REJECTED_USER, QUOTE_APPROVED_ADMIN, QUOTE_REFUSED_ADMIN

}
/*
 * QuoteSent then(QUOTE_ACCEPTED_PARTNER OR QUOTE_REJECTED_PARTNER)
 * then(QUOTE_APPROVED_ADMIN OR QUOTE_REFUSED_ADMIN)if(approved)then(
 * (QUOTE_ACCEPTED_USER OR QUOTE_Rejected_USER
 */