package ilab.core.domain;

public enum OrderStatus
{
	SHOPPING_CART,WISH_LIST,WAIT_QUOTE,WAIT_CONFIRMATION,PENDING,IN_PROGRESS,PARTIALLY_FINISHED,FINISHED,PARIALLY_DELIVERED,DELIVERED,CANCELLED,REJECT_ORDER,REJECT_QUOTE
}
